
services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Wait for db to be healthy
    environment:
      - DEBUG=True
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Named volume for PostgreSQL data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  ppgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Named volume for pgAdmin configuration
    depends_on:
      - db

volumes:
  postgres_data:  # Volume for PostgreSQL data
  pgadmin_data: # Volume for pgAdmin configuration
