# Generated by Django 5.1.7 on 2025-05-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='campus_involvement',
            field=models.TextField(blank=True),
        ),
    ]
