# Generated by Django 5.1.6 on 2025-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_customuser_achievements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="maximum_capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of attendees (leave blank for unlimited)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="required_materials",
            field=models.TextField(
                blank=True,
                help_text="List any materials participants should bring or prepare",
            ),
        ),
    ]
