# Generated by Django 5.2 on 2025-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_customuser_city_customuser_postcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End date and time of the event', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='Start date and time of the event'),
        ),
    ]
