# Generated by Django 5.2 on 2025-05-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_customuser_profile_image'),
        ('myapp', '0010_event_end_date_alter_event_date'),
    ]

    operations = [
    ]
